#!/bin/bash
#
# laps, nooruk, täiskasvanu või seenjor
#
echo -n "sisestage oma vanus: " # tuleb sisestada oma vanus
read x # loeb sisestatud arvu
if (( $x < 11 )) || (( $x == 11 )); # kui arv on väiksem kui 11 või võrde 11
then echo "te olete laps" # siis väljastatakse te olete laps
elif (( $x == 12 )) || (( $x < 18 )); # ja kui arv on väiksem kui 18 või võrdne 12
then echo "te olete nooruk" # siis väljastatakse te olete nooruk
elif (( $x == 63 )) || (( $x > 63)); # kui arv on võrdne või suurem kui 63 
then echo "te olete seenjor" # siis väljastatakse te olete seenjor
else echo "te olete täiskasvanu" # kui arv jääb 18 ja 63 vahele, siis väljastatakse te olete täiskasvanu
fi # if commandi lõpp 
#
# skripti lõpp
#
