#!/bin/bash
#
# kuu väljastamine
echo "siseta kuu number: " # tuleb sisestada kuu numbri
read kuu # loeb sisestatut
case $kuu in # vaatab sisetataud väärtust ja võrdleb kokkulangevust alla olevate tingimustega
"1") echo "jaanuar";;
"2") echo "veebruar";;
"3") echo "märts";;
"4") echo "aprill";;
"5") echo "mai";;
"6") echo "juuni";;
"7") echo "juuli";;
"8") echo "august";;
"9") echo "september";;
"10") echo "oktoober";;
"11") echo "november";;
"12") echo "dersember";;
*) echo " vale sisend " # kui sisetatud ei lange kokku ühegi tingimusega siis väljastatakse vale sisend
esac # case commandi lõpp
# skripti lõpp
