#!/bin/bash
#
# minu muljed
#
echo  "Ago Anderson" # välastab reavhetusega Ago Anderson
echo  "ISP118" # väljastab reavahetusega ISP118
echo  "Aine tundub huvitav" # väljastab reavahetusega Aine tundub huvitav
#
# skripti lõpp
